/**
 * Error Codes for UniHood API
 * * Rule 8: Backend returns error codes, Frontend maps to localized Vietnamese strings
 * Format: { success: false, code: ErrorCodes.XYZ, error: 'Technical debug info (English)' }
 */

export enum ErrorCodes {
  // ========== Authentication & Authorization ==========
  AUTH_NO_TOKEN = "AUTH_NO_TOKEN",
  AUTH_INVALID_TOKEN = "AUTH_INVALID_TOKEN",
  AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED",
  AUTH_USER_NOT_FOUND = "AUTH_USER_NOT_FOUND",
  AUTH_UNAUTHORIZED = "AUTH_UNAUTHORIZED",
  AUTH_FORBIDDEN = "AUTH_FORBIDDEN",
  AUTH_GOOGLE_CODE_REQUIRED = "AUTH_GOOGLE_CODE_REQUIRED",
  AUTH_GOOGLE_EXCHANGE_FAILED = "AUTH_GOOGLE_EXCHANGE_FAILED",
  AUTH_SESSION_CREATION_FAILED = "AUTH_SESSION_CREATION_FAILED",
  AUTH_EMAIL_NOT_AVAILABLE = "AUTH_EMAIL_NOT_AVAILABLE",

  // ========== Profile & User ==========
  PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND",
  PROFILE_CREATION_FAILED = "PROFILE_CREATION_FAILED",
  PROFILE_UPDATE_FAILED = "PROFILE_UPDATE_FAILED",
  PROFILE_ALREADY_EXISTS = "PROFILE_ALREADY_EXISTS",
  PROFILE_VERIFICATION_PENDING = "PROFILE_VERIFICATION_PENDING",
  PROFILE_VERIFICATION_REJECTED = "PROFILE_VERIFICATION_REJECTED",
  PROFILE_NOT_VERIFIED = "PROFILE_NOT_VERIFIED",
  PROFILE_DELETED = "PROFILE_DELETED",

  // ========== Wallet & Transactions (Rule 3 & 11) ==========
  WALLET_INSUFFICIENT = "WALLET_INSUFFICIENT",
  WALLET_NOT_FOUND = "WALLET_NOT_FOUND",
  WALLET_LOCKED = "WALLET_LOCKED", // Khi đang xử lý transaction khác
  WALLET_CREATION_FAILED = "WALLET_CREATION_FAILED",
  TRANSACTION_FAILED = "TRANSACTION_FAILED",
  TRANSACTION_INVALID = "TRANSACTION_INVALID",
  TRANSACTION_NOT_FOUND = "TRANSACTION_NOT_FOUND",
  ESCROW_DISPUTED = "ESCROW_DISPUTED", // Khi giao dịch Marketplace bị khiếu nại
  ESCROW_ALREADY_RELEASED = "ESCROW_ALREADY_RELEASED",

  // ========== Products & Marketplace ==========
  PRODUCT_NOT_FOUND = "PRODUCT_NOT_FOUND",
  PRODUCT_CREATION_FAILED = "PRODUCT_CREATION_FAILED",
  PRODUCT_UPDATE_FAILED = "PRODUCT_UPDATE_FAILED",
  PRODUCT_NOT_APPROVED = "PRODUCT_NOT_APPROVED",
  PRODUCT_ALREADY_SOLD = "PRODUCT_ALREADY_SOLD",
  PRODUCT_CANNOT_BUY_OWN = "PRODUCT_CANNOT_BUY_OWN",
  PRODUCT_DELETED = "PRODUCT_DELETED",
  MARKETPLACE_ACCESS_DENIED = "MARKETPLACE_ACCESS_DENIED",

  // ========== Posts & Social (Rule 3: Anti-Spam) ==========
  POST_NOT_FOUND = "POST_NOT_FOUND",
  POST_CREATION_FAILED = "POST_CREATION_FAILED",
  POST_UPDATE_FAILED = "POST_UPDATE_FAILED",
  POST_CONTENT_EMPTY = "POST_CONTENT_EMPTY",
  POST_DUPLICATE_CONTENT = "POST_DUPLICATE_CONTENT", // Content hash match
  POST_DELETED = "POST_DELETED",
  POST_VISIBILITY_RESTRICTED = "POST_VISIBILITY_RESTRICTED",

  // ========== Comments ==========
  COMMENT_NOT_FOUND = "COMMENT_NOT_FOUND",
  COMMENT_CREATION_FAILED = "COMMENT_CREATION_FAILED",
  COMMENT_UPDATE_FAILED = "COMMENT_UPDATE_FAILED",
  COMMENT_CONTENT_EMPTY = "COMMENT_CONTENT_EMPTY",
  COMMENT_DELETED = "COMMENT_DELETED",

  // ========== Reviews ==========
  REVIEW_NOT_FOUND = "REVIEW_NOT_FOUND",
  REVIEW_CREATION_FAILED = "REVIEW_CREATION_FAILED",
  REVIEW_UPDATE_FAILED = "REVIEW_UPDATE_FAILED",
  REVIEW_INVALID_RATING = "REVIEW_INVALID_RATING",
  REVIEW_DELETED = "REVIEW_DELETED",

  // ========== Verification (Rule 4 & 5) ==========
  VERIFICATION_PROOF_REQUIRED = "VERIFICATION_PROOF_REQUIRED",
  VERIFICATION_ALREADY_SUBMITTED = "VERIFICATION_ALREADY_SUBMITTED",
  VERIFICATION_NOT_PENDING = "VERIFICATION_NOT_PENDING",
  VERIFICATION_STUDENT_CODE_INVALID = "VERIFICATION_STUDENT_CODE_INVALID",
  VERIFICATION_OCR_FAILED = "VERIFICATION_OCR_FAILED",
  VERIFICATION_DOMAIN_MISMATCH = "VERIFICATION_DOMAIN_MISMATCH", // Email .edu.vn ko khớp

  // ========== Multi-tenancy (Rule 3) ==========
  SCHOOL_NOT_FOUND = "SCHOOL_NOT_FOUND",
  SCHOOL_ACCESS_DENIED = "SCHOOL_ACCESS_DENIED", // Sinh viên trường A xem dữ liệu trường B

  // ========== Idempotency (Rule 7) ==========
  IDEMPOTENCY_KEY_REQUIRED = "IDEMPOTENCY_KEY_REQUIRED",
  IDEMPOTENCY_KEY_CONFLICT = "IDEMPOTENCY_KEY_CONFLICT", // Đang xử lý hoặc đã xong

  // ========== Reports ==========
  REPORT_CREATION_FAILED = "REPORT_CREATION_FAILED",
  REPORT_NOT_FOUND = "REPORT_NOT_FOUND",
  REPORT_INVALID_TYPE = "REPORT_INVALID_TYPE",
  REPORT_REASON_REQUIRED = "REPORT_REASON_REQUIRED",

  // ========== Relationships & Matches ==========
  RELATIONSHIP_NOT_FOUND = "RELATIONSHIP_NOT_FOUND",
  RELATIONSHIP_ALREADY_EXISTS = "RELATIONSHIP_ALREADY_EXISTS",
  RELATIONSHIP_CANNOT_FOLLOW_SELF = "RELATIONSHIP_CANNOT_FOLLOW_SELF",
  MATCH_NOT_FOUND = "MATCH_NOT_FOUND",

  // ========== Messages & Chat ==========
  MESSAGE_NOT_FOUND = "MESSAGE_NOT_FOUND",
  MESSAGE_CREATION_FAILED = "MESSAGE_CREATION_FAILED",
  CONVERSATION_NOT_FOUND = "CONVERSATION_NOT_FOUND",
  CONVERSATION_ACCESS_DENIED = "CONVERSATION_ACCESS_DENIED",

  // ========== Notifications ==========
  NOTIFICATION_NOT_FOUND = "NOTIFICATION_NOT_FOUND",
  NOTIFICATION_CREATION_FAILED = "NOTIFICATION_CREATION_FAILED",

  // ========== Validation Errors ==========
  VALIDATION_REQUIRED = "VALIDATION_REQUIRED",
  VALIDATION_INVALID_TYPE = "VALIDATION_INVALID_TYPE",
  VALIDATION_INVALID_FORMAT = "VALIDATION_INVALID_FORMAT",
  VALIDATION_INVALID_VALUE = "VALIDATION_INVALID_VALUE",
  VALIDATION_TOO_LONG = "VALIDATION_TOO_LONG",
  VALIDATION_TOO_SHORT = "VALIDATION_TOO_SHORT",

  // ========== Resource Not Found ==========
  RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND",
  RESOURCE_DELETED = "RESOURCE_DELETED",

  // ========== Permission & Tiers (Rule 4) ==========
  PERMISSION_DENIED = "PERMISSION_DENIED",
  PERMISSION_INSUFFICIENT_TRUST = "PERMISSION_INSUFFICIENT_TRUST",
  PERMISSION_TIER_TOO_LOW = "PERMISSION_TIER_TOO_LOW", // VD: Tier 1 ko đc vào Marketplace
  PERMISSION_NOT_OWNER = "PERMISSION_NOT_OWNER",
  PERMISSION_NOT_ADMIN = "PERMISSION_NOT_ADMIN",
  PERMISSION_FORBIDDEN_ROLE = "PERMISSION_FORBIDDEN_ROLE", // Role không phù hợp (e.g. student ko đc recruiter endpoint)
  PERMISSION_VERIFICATION_REQUIRED = "PERMISSION_VERIFICATION_REQUIRED", // Tier 1+ yêu cầu verify

  // ========== Configuration & System ==========
  CONFIG_SUPABASE_MISSING = "CONFIG_SUPABASE_MISSING",
  CONFIG_DATABASE_UNAVAILABLE = "CONFIG_DATABASE_UNAVAILABLE",
  CONFIG_REDIS_UNAVAILABLE = "CONFIG_REDIS_UNAVAILABLE",
  CONFIG_R2_UNAVAILABLE = "CONFIG_R2_UNAVAILABLE",
  CONFIG_AI_SERVICE_UNAVAILABLE = "CONFIG_AI_SERVICE_UNAVAILABLE",

  // ========== Server & System ==========
  INTERNAL_ERROR = "INTERNAL_ERROR",
  DATABASE_ERROR = "DATABASE_ERROR",
  EXTERNAL_SERVICE_ERROR = "EXTERNAL_SERVICE_ERROR",
  QUEUE_PROCESSING_ERROR = "QUEUE_PROCESSING_ERROR",
  RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED",

  // ========== Upload Errors (Rule 12) ==========
  UPLOAD_FILE_TOO_LARGE = "UPLOAD_FILE_TOO_LARGE",
  UPLOAD_INVALID_TYPE = "UPLOAD_INVALID_TYPE",
  UPLOAD_FAILED = "UPLOAD_FAILED",
  UPLOAD_PRESIGN_FAILED = "UPLOAD_PRESIGN_FAILED",
}

/**
 * Standard API Error Response Format
 * Backend should return errors in this format
 */
export interface ApiErrorResponse {
  success: false;
  code: ErrorCodes;
  error: string; // Technical debug info in English
  details?: unknown; // Optional additional error details
}

/**
 * Standard API Success Response Format
 */
export interface ApiSuccessResponse<T = unknown> {
  success: true;
  data: T;
}

/**
 * Union type for API responses
 */
export type ApiResponse<T = unknown> = ApiSuccessResponse<T> | ApiErrorResponse;

/**
 * Helper function to create error response
 */
export function createErrorResponse(
  code: ErrorCodes,
  error: string,
  details?: unknown
): ApiErrorResponse {
  const response: ApiErrorResponse = {
    success: false,
    code,
    error,
  };
  if (details !== undefined) {
    response.details = details;
  }
  return response;
}

/**
 * Helper function to create success response
 */
export function createSuccessResponse<T>(data: T): ApiSuccessResponse<T> {
  return {
    success: true,
    data,
  };
}
